# Generated by Django 5.1.1 on 2024-10-05 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id_envio', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('direccion_destino', models.CharField(max_length=255)),
                ('fecha_envio', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_producto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoTransporte',
            fields=[
                ('id_tipo_transporte', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('transporte', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moniweb.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moniweb.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tipo_pago', models.CharField(choices=[('credito', 'Credito'), ('efectivo', 'Efectivo')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moniweb.cliente')),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moniweb.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id_paquete', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dimensiones', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('id_envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moniweb.envio')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moniweb.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='id_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moniweb.pedido'),
        ),
        migrations.AddField(
            model_name='envio',
            name='id_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moniweb.pedido'),
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id_sede', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('id_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moniweb.ciudad')),
            ],
        ),
        migrations.AddField(
            model_name='envio',
            name='id_sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moniweb.sede'),
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id_transportista', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('id_tipo_transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moniweb.tipotransporte')),
            ],
        ),
        migrations.AddField(
            model_name='envio',
            name='id_transportista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moniweb.transportista'),
        ),
        migrations.CreateModel(
            name='PedPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moniweb.pedido')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moniweb.producto')),
            ],
            options={
                'unique_together': {('id_pedido', 'id_producto')},
            },
        ),
        migrations.CreateModel(
            name='PaquPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moniweb.paquete')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moniweb.producto')),
            ],
            options={
                'unique_together': {('id_producto', 'id_paquete')},
            },
        ),
    ]
